### ISSUE TITLE
Drawing Points/Vertices?

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto.Veldrid#6]
I hunted around to see what might be possible here, but couldn't find a good answer up to now. The etoViewport/Eto.OpenTK code allows for points to be overlaid on the underlying polygons (using a separate draw). Is there a way to reproduce this in Veldrid?

**Comment by philstopford** [comment]
https://github.com/ItEndsWithTens/Eto.Veldrid/pull/7

Can't figure out how to make large points

**Comment by ItEndsWithTens** [comment]
From what I'm reading looking into this, it's not a feature supported reliably by anything except OpenGL. Vulkan supports it if the hardware has certain features, D3D11 doesn't do it at all, and I'm not sure about Metal at the moment.

Veldrid therefore has no built in support for doing it, but there are ways around the limitation, I think.

1. If one is only going to use OpenGL, or Vulkan with [the appropriate hardware features](https://stackoverflow.com/a/44575227), you can do it through the shaders. In src/shaders/VertexColor-vertex.450.glsl, [just below the gl_Position assignment](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/434702cf703e408ae0b91c54c6904831ef6e7346/src/shaders/VertexColor-vertex.450.glsl#L21), add e.g.
 ```
 gl_PointSize = 4.0f;
 ```
This only draws squares, but you can adjust the size that way for APIs that support it.

2. Write a geometry shader to emit polygons for each point you want to render. I haven't even begun studying such shaders, however, so I can't offer advice on them just yet. I do know driver support for geometry shaders is required, and not all hardware offers that, namely many mobile devices. If your target is desktop, though, I suspect you could rely on it being available.

3. Make your own "point" by creating a square or circle polygon, or cube, sphere, or really whatever you'd like, and use geometry instancing to place copies of it at the appropriate vertex positions. Instancing is another feature I've never worked with. I imagine trying to keep instances the right size in screen space would be its own challenge, since instances would be placed at the actual vertex locations, which means 3D points further from the camera would appear smaller.

Despite my lack of experience, I think those three are arranged in order of increasing cross-backend support, device compatibility, and difficulty. But take that with a grain of salt! I could easily be wrong.

**Comment by philstopford** [comment]
I've gone with a mildly ugly hack for now. https://github.com/ItEndsWithTens/Eto.Veldrid/pull/8
